### ISSUE TITLE
Randomized layouts are being reused due to seed generation

### ISSUE THREAD

**Issue by ghost** [datarail/datarail#31]
I noticed that when generating replicate plates the random seed is reused for each new instance based on this code in process_assay.py:

for rep_num, plate in enumerate(plate_names):
    np.random.seed(rep_num+1)

I am not sure if this was by design but it generates the same randomization layouts for each new experimental setup.

**Comment by smkartik** [comment]
for `plate names = ['plate1', 'plate2', 'plate3']`, the code will generate 3 different randomized layouts using random seed 0, 1 and 2 respectively. This is by design. The randomization scheme will be repeated for an entirely new experiment. This is by design. Do you want to have different random seeds for each new experiment?
